# Generated by Django 5.1.7 on 2025-03-24 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form13FStockInvestmentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.BigIntegerField()),
                ('investor_cik', models.CharField(max_length=13)),
                ('investor_name', models.TextField()),
                ('investor_former_names', models.JSONField(default=list)),
                ('investor_country', models.CharField()),
                ('investor_region', models.CharField()),
                ('other_investor_numbers', models.JSONField(default=list)),
                ('other_investor_names', models.JSONField(default=list)),
                ('form_accession_number', models.TextField()),
                ('form_report_date', models.DateField(null=True)),
                ('form_filing_date', models.DateField(null=True)),
                ('stock_issuer', models.CharField()),
                ('stock_cusip', models.CharField(max_length=9)),
                ('stock_figi', models.CharField(blank=True, default='')),
                ('stock_ticker', models.CharField(blank=True, default='')),
                ('stock_description', models.CharField(blank=True, default='')),
                ('stock_value_x1000', models.BigIntegerField()),
                ('stock_shares_prn_amt', models.BigIntegerField()),
                ('stock_sh_prn', models.CharField()),
                ('stock_voting_auth_sole', models.BigIntegerField(null=True)),
                ('stock_voting_auth_shared', models.BigIntegerField(null=True)),
                ('stock_voting_auth_none', models.BigIntegerField(null=True)),
                ('stock_exchange_codes', models.JSONField(default=list)),
                ('form_url', models.URLField()),
            ],
            options={
                'db_table': 'form_13f_stock_investment_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdgarCusipMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='')),
                ('cusip', models.CharField()),
                ('figi', models.CharField(blank=True, default='')),
                ('composite_figi', models.CharField(blank=True, default='')),
                ('share_class_figi', models.CharField(blank=True, default='')),
                ('ticker', models.CharField(blank=True, default='')),
                ('exchange_codes', models.JSONField(default=list)),
                ('market_sector', models.CharField(blank=True, default='')),
                ('security_type', models.CharField(blank=True, default='')),
                ('security_type_2', models.CharField(blank=True, default='')),
                ('security_description', models.CharField(blank=True, default='')),
            ],
            options={
                'db_table': 'edgar_cusip_mapping',
                'constraints': [models.UniqueConstraint(fields=('cusip',), name='unique_edgar_cusip_mapping')],
            },
        ),
        migrations.CreateModel(
            name='EdgarPlaceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField()),
                ('country', models.CharField()),
                ('state', models.CharField()),
            ],
            options={
                'db_table': 'edgar_place_code',
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_edgar_place_code'), models.UniqueConstraint(fields=('country', 'state'), name='unique_edgar_place')],
            },
        ),
        migrations.CreateModel(
            name='ScrapedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cik', models.CharField(max_length=13)),
                ('name', models.TextField()),
                ('former_names', models.JSONField(default=list)),
                ('street', models.CharField(blank=True)),
                ('secondary', models.CharField(blank=True)),
                ('city', models.CharField(blank=True)),
                ('state_or_country', models.CharField()),
                ('zip_code', models.CharField(blank=True)),
            ],
            options={
                'db_table': 'scraped_company',
                'constraints': [models.UniqueConstraint(fields=('cik',), name='unique_scraped_company_cik')],
            },
        ),
        migrations.CreateModel(
            name='ScrapedCompanyFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.TextField(choices=[('13F-HR', 'Form 13F Hr')])),
                ('accession_number', models.TextField()),
                ('report_date', models.DateField(null=True)),
                ('filing_date', models.DateField(null=True)),
                ('url', models.URLField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.scrapedcompany')),
            ],
            options={
                'db_table': 'scraped_form_submission',
            },
        ),
        migrations.CreateModel(
            name='ScrapedForm13FManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('number', models.IntegerField()),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.scrapedcompanyfiling')),
            ],
            options={
                'db_table': 'scraped_form_13f_manager',
            },
        ),
        migrations.CreateModel(
            name='ScrapedForm13FStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_name', models.CharField()),
                ('title_class', models.CharField(blank=True)),
                ('cusip', models.CharField(max_length=9)),
                ('value_x1000', models.BigIntegerField()),
                ('shares_prn_amt', models.BigIntegerField()),
                ('sh_prn', models.CharField()),
                ('put_call', models.CharField(blank=True)),
                ('investment_discretion', models.CharField()),
                ('other_manager', models.CharField(blank=True)),
                ('voting_auth_sole', models.BigIntegerField(null=True)),
                ('voting_auth_shared', models.BigIntegerField(null=True)),
                ('voting_auth_none', models.BigIntegerField(null=True)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.scrapedcompanyfiling')),
            ],
            options={
                'db_table': 'scraped_form_13f_investment',
            },
        ),
        migrations.CreateModel(
            name='CleanForm13StockManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.scrapedform13fstock')),
            ],
            options={
                'db_table': 'clean_form_13f_stock_manager',
            },
        ),
        migrations.AddConstraint(
            model_name='scrapedcompanyfiling',
            constraint=models.UniqueConstraint(fields=('accession_number',), name='unique_scraped_filing_accession_number'),
        ),
        migrations.AddConstraint(
            model_name='scrapedform13fstock',
            constraint=models.UniqueConstraint(fields=('filing', 'cusip', 'investment_discretion', 'other_manager'), name='unique_scraped_form_13f_stock'),
        ),
        migrations.AddIndex(
            model_name='cleanform13stockmanager',
            index=models.Index(fields=['stock'], name='clean_form__stock_i_203fb8_idx'),
        ),
        migrations.AddConstraint(
            model_name='cleanform13stockmanager',
            constraint=models.UniqueConstraint(fields=('stock', 'name'), name='unique_clean_form_13f_stock_manager'),
        ),
    ]
