# Generated by Django 5.1.1 on 2024-09-14 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cik', models.CharField(max_length=13)),
                ('name', models.TextField()),
                ('former_names', models.JSONField(default=[])),
                ('street', models.CharField(blank=True)),
                ('secondary', models.CharField(blank=True)),
                ('city', models.CharField(blank=True)),
                ('state_or_country', models.CharField()),
                ('zip_code', models.CharField(blank=True)),
            ],
            options={
                'db_table': 'scraped_company',
                'constraints': [models.UniqueConstraint(fields=('cik',), name='unique_scraped_company_cik')],
            },
        ),
        migrations.CreateModel(
            name='ScrapedCompanyFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.TextField(choices=[('13F-HR', 'Form 13F Hr')])),
                ('accession_number', models.TextField()),
                ('report_date', models.DateField(null=True)),
                ('filing_date', models.DateField(null=True)),
                ('url', models.URLField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.scrapedcompany')),
            ],
            options={
                'db_table': 'scraped_form_submission',
            },
        ),
        migrations.CreateModel(
            name='ScrapedForm13FStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_name', models.CharField()),
                ('title_class', models.CharField(blank=True)),
                ('cusip', models.CharField(max_length=9)),
                ('value_x1000', models.IntegerField()),
                ('shares_prn_amt', models.IntegerField()),
                ('sh_prn', models.CharField()),
                ('put_call', models.CharField(blank=True)),
                ('investment_discretion', models.CharField()),
                ('manager', models.CharField(blank=True)),
                ('voting_auth_sole', models.IntegerField(null=True)),
                ('voting_auth_shared', models.IntegerField(null=True)),
                ('voting_auth_none', models.IntegerField(null=True)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.scrapedcompanyfiling')),
            ],
            options={
                'db_table': 'scraped_form_13f_investment',
            },
        ),
        migrations.AddConstraint(
            model_name='scrapedcompanyfiling',
            constraint=models.UniqueConstraint(fields=('accession_number',), name='unique_scraped_filing_accession_number'),
        ),
        migrations.AddConstraint(
            model_name='scrapedform13fstock',
            constraint=models.UniqueConstraint(fields=('filing', 'cusip', 'investment_discretion', 'manager'), name='unique_scraped_form13f_stock'),
        ),
    ]
