# Generated by Django 5.1.1 on 2024-09-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedcompany',
            name='former_names',
            field=models.JSONField(default=list),
        ),
    ]
