# Generated by Django 5.1.1 on 2024-09-16 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_alter_scrapedcompany_former_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapedform13fstock',
            old_name='manager',
            new_name='other_manager',
        ),
    ]
