# Generated by Django 5.1.1 on 2024-09-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0003_rename_manager_scrapedform13fstock_other_manager'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scrapedform13fstock',
            name='unique_scraped_form13f_stock',
        ),
        migrations.AddConstraint(
            model_name='scrapedform13fstock',
            constraint=models.UniqueConstraint(fields=('filing', 'cusip', 'investment_discretion', 'other_manager'), name='unique_scraped_form13f_stock'),
        ),
    ]
