# Generated by Django 5.1.1 on 2024-09-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0004_remove_scrapedform13fstock_unique_scraped_form13f_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedform13fstock',
            name='shares_prn_amt',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='scrapedform13fstock',
            name='value_x1000',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='scrapedform13fstock',
            name='voting_auth_none',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scrapedform13fstock',
            name='voting_auth_shared',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scrapedform13fstock',
            name='voting_auth_sole',
            field=models.BigIntegerField(null=True),
        ),
    ]
