# Generated by Django 5.1.1 on 2024-09-18 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0006_cusipmapping_edgarplacecode_scrapedform13fmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanForm13StockManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
            options={
                'db_table': 'clean_form_13f_stock_manager',
            },
        ),
        migrations.RenameModel(
            old_name='CusipMapping',
            new_name='EdgarCusipMapping',
        ),
        migrations.RemoveConstraint(
            model_name='edgarcusipmapping',
            name='unique_cusip_mapping',
        ),
        migrations.RemoveConstraint(
            model_name='scrapedform13fstock',
            name='unique_scraped_form13f_stock',
        ),
        migrations.AddConstraint(
            model_name='edgarcusipmapping',
            constraint=models.UniqueConstraint(fields=('cusip',), name='unique_edgar_cusip_mapping'),
        ),
        migrations.AddConstraint(
            model_name='scrapedform13fstock',
            constraint=models.UniqueConstraint(fields=('filing', 'cusip', 'investment_discretion', 'other_manager'), name='unique_scraped_form_13f_stock'),
        ),
        migrations.AlterModelTable(
            name='edgarcusipmapping',
            table='edgar_cusip_mapping',
        ),
        migrations.AlterModelTable(
            name='scrapedform13fmanager',
            table='scraped_form_13f_manager',
        ),
        migrations.AddField(
            model_name='cleanform13stockmanager',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.scrapedform13fstock'),
        ),
        migrations.AddConstraint(
            model_name='cleanform13stockmanager',
            constraint=models.UniqueConstraint(fields=('stock', 'name'), name='unique_clean_form_13f_stock_manager'),
        ),
    ]
