# Generated by Django 5.1.1 on 2024-09-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0007_cleanform13stockmanager_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cleanform13stockmanager',
            index=models.Index(fields=['stock'], name='clean_form__stock_i_203fb8_idx'),
        ),
    ]
