# Generated by Django 5.1.1 on 2024-09-14 00:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_execution', models.CharField()),
                ('type', models.CharField(choices=[('Scrape Bulk Submissions', 'Scrape Bulk Submissions')])),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Error', 'Error'), ('Success', 'Success')], default='In Progress')),
                ('started_at_utc', models.DateTimeField(auto_now_add=True)),
                ('ended_at_utc', models.DateTimeField(null=True)),
                ('last_error_at_utc', models.DateTimeField(null=True)),
                ('error', models.TextField(null=True)),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
