# Generated by Django 5.1.7 on 2025-03-24 23:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_execution', models.CharField()),
                ('type', models.CharField(choices=[('Fetch Form 13F Stock Metadata', 'Fetch Form 13F Stock Metadata'), ('Scrape Bulk Submissions', 'Scrape Bulk Submissions'), ('Scrape Form 13F Cover Page', 'Scrape Form 13F Cover Page'), ('Scrape Form 13F Filing Details', 'Scrape Form 13F Filing Details'), ('Scrape Form 13F Stocks', 'Scrape Form 13F Stocks')])),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Error', 'Error'), ('Success', 'Success')], default='In Progress')),
                ('started_at_utc', models.DateTimeField(auto_now_add=True)),
                ('ended_at_utc', models.DateTimeField(null=True)),
                ('last_error_at_utc', models.DateTimeField(null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('num_retries', models.IntegerField(default=0)),
                ('url', models.URLField(null=True)),
            ],
            options={
                'db_table': 'task',
                'constraints': [models.UniqueConstraint(fields=('workflow_execution', 'type', 'url'), name='unique_task')],
            },
        ),
    ]
