# Generated by Django 5.1.1 on 2024-09-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('Scrape Bulk Submissions', 'Scrape Bulk Submissions'), ('Scrape Filing Details', 'Scrape Filing Details')]),
        ),
    ]
