# Generated by Django 5.1.1 on 2024-09-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_task_url_alter_task_error_alter_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('Scrape Bulk Submissions', 'Scrape Bulk Submissions'), ('Scrape Form 13F Filing Details', 'Scrape Form 13F Filing Details'), ('Scrape Form 13F Stocks', 'Scrape Form 13F Stocks')]),
        ),
    ]
