# Generated by Django 5.1.1 on 2024-09-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='num_retries',
            field=models.IntegerField(default=0),
        ),
    ]
